### ISSUE TITLE
Can't build for iOS with app_type: rhoelements

### ISSUE THREAD

**Issue by pascalw** [rhomobile/rhoelements-issues#69]
Hello,

I'm upgrading a RhoMobile 2 application to RhoMobile 4. If I try to build for iOS from XCode I get the following exception:

```
...

ext - barcode
exception: cannot load such file -- barcode
********* WARNING *****************************************************************************************************
The following extensions do not have JavaScript API: 
digest
digest-sha1
Use RMS 4.0 extensions to provide JavaScript API
***********************************************************************************************************************
********* WARNING ************************************************************************
 The following features are only available in RhoElements v2 and above:
- Barcode extension
- Indicators extension
- HardwareKeys extension
- Audio Capture
 For more information go to http://www.motorolasolutions.com/rhoelements 
******************************************
```

I'm **not** using the barcode api though.

My build.yml looks like this (abbreviated):

```

---
sdkversion: 4.0.0
iphone:
  configuration: Release
  sdk: iphonesimulator6.1
  capabilities:
    - non_motorola_device
    - native_browser
    - camera
android:
  android_title: 0
  version: 2.1
  capabilities:
    - non_motorola_device
    - native_browser
    - camera
    - hardware_acceleration
extensions:
  - coreapi
  - mspec
  - fileutils
  - json
  - rholang
  - digest
  - "digest-sha1"
motorola_license: ...
app_type: rhoelements
capabilities:
  - bluetooth
  - gps
  - vibrate
```

Removing the app_tye: rhoelements line allows the app to build, but I do need some of the rhoelements APIs. Any ideas what's causing this and how I can fix it?
